---
- hosts: local
  become: true
  tasks:

    - name: Git pull main repo
      git: repo=git@github.com:welenofsky/portfolio.git
           dest=/{{ username }}/sites/{{ host }}/source/
           accept_hostkey=True
           key_file=/home/{{ username }}/.ssh/id_rsa
           update=True
      notify:
        - restart gunicorn

    - name: Git pull secrets
      git: repo=git@github.com:welenofsky/portfolio-secrets.git
           dest=/{{ username }}/sites/{{ host }}/secrets/
           accept_hostkey=True
           key_file=/home/{{ username }}/.ssh/id_rsa
           update=True

    - name: Pip install requirements file
      pip: requirements=/{{ username }}/sites/{{ host }}/source/portfolio/{{ requirements }}
           virtualenv=/{{ username }}/sites/{{ host }}/virtualenv

    - name: Update static files
      shell: '../../virtualenv/bin/python3 manage.py collectstatic --noinput  --settings={{ settings }}'
      args:
        chdir: /{{ username }}/sites/{{ host }}/source/portfolio
      notify:
        - restart nginx
        - restart gunicorn

    - name: Apply db migrations
      shell: '../../virtualenv/bin/python3 manage.py migrate --noinput --settings={{ settings }}'
      args:
        chdir: /{{ username }}/sites/{{ host }}/source/portfolio
      notify:
        - restart nginx
        - restart gunicorn

    - name: Make sure nginx is running
      service: name=nginx state=running

    - name: Make sure gunicorn is running
      service: name=gunicorn-{{ host }} state=running

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart gunicorn
      service: name=gunicorn-{{ host }} state=restarted


- hosts:
  - staging
  - live
  become: true
  tasks:

    - name: Git pull main repo
      git: repo=git@github.com:welenofsky/portfolio.git
           dest=/home/{{ username }}/sites/{{ host }}/source/
           accept_hostkey=True
           key_file=/home/{{ username }}/.ssh/id_rsa
           update=True
      notify:
        - restart gunicorn

    - name: Git pull secrets
      git: repo=git@github.com:welenofsky/portfolio-secrets.git
           dest=/home/{{ username }}/sites/{{ host }}/secrets/
           accept_hostkey=True
           key_file=/home/{{ username }}/.ssh/id_rsa
           update=True

    - name: Pip install requirements file
      pip: requirements=/home/{{ username }}/sites/{{ host }}/source/portfolio/{{ requirements }}
           virtualenv=/home/{{ username }}/sites/{{ host }}/virtualenv

    - name: Update static files
      shell: '../../virtualenv/bin/python3 manage.py collectstatic --noinput --settings={{ settings }}'
      args:
        chdir: /home/{{ username }}/sites/{{ host }}/source/portfolio
      notify:
        - restart nginx
        - restart gunicorn

    - name: Apply db migrations
      shell: '../../virtualenv/bin/python3 manage.py collectstatic --noinput  --settings={{ settings }}'
      args:
        chdir: /home/{{ username }}/sites/{{ host }}/source/portfolio
      notify:
        - restart nginx
        - restart gunicorn

    - name: Make sure nginx is running
      service: name=nginx state=running

    - name: Make sure gunicorn is running
      service: name=gunicorn-{{ host }} state=running

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart gunicorn
      service: name=gunicorn-{{ host }} state=restarted
