---
- hosts: local
  become: true
  tasks:
    - name: Upgrade cache and system (safe upgrade)
      apt: upgrade=safe update_cache=yes

    - name: Install git/php5/mysql
      apt: pkg=nginx,git,php5,php5-fpm,mysql-server state=present

    - name: Installing build-tools
      apt: pkg=build-essential,autoconf,libtool,pkg-config,libpq-dev,python-mysqldb

    - name: Ensure MySQL is running
      service: name=mysql state=started enabled=true

    - name: Create a new database with name 'pipeline'
      mysql_db:
        name: pipeline
        state: present
      notify:
          - restart mysql

    - name: Remove nginx default if exists
      shell: '[ ! -f default ] || rm default'
      args:
        chdir: /etc/nginx/sites-available/

    - name: Add nginx config to sites-available
      template: src=./nginx.conf.j2
                dest=/etc/nginx/sites-available/{{ host }}
      notify:
          - restart nginx
          - restart php5fpm

    - name: Add symlink in nginx sites-enabled
      file: src=/etc/nginx/sites-available/{{ host }}
            dest=/etc/nginx/sites-enabled/{{ host }} state=link
      notify:
          - restart nginx
          - restart php5fpm

    - name: Make sure nginx is running
      service: name=nginx state=running

    - name: Make sure php5-fpm is running
      service: name=php5-fpm state=running

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted

    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart php5fpm
      service: name=php5-fpm state=restarted